import type { CatalogProduct } from "@interior/domain";

export const seedProducts: CatalogProduct[] = [
  {
    id: "bed_walnut_platform",
    name: "Walnut Platform Bed",
    category: "bed_frame",
    retailerId: "demo_home",
    retailerName: "Demo Home",
    source: "demo",
    priceCents: 57900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/walnut-platform-bed",
    dimensions: { widthIn: 64, depthIn: 84, heightIn: 38 },
    materials: ["walnut veneer", "wood slats"],
    colors: ["walnut", "brown"],
    styleTags: ["japandi-calm", "cozy-neutral", "warm-modern"],
    roomTags: ["bedroom"],
    availability: "in_stock",
    shippingDaysEstimate: 7,
    dimensionConfidence: 0.97
  },
  {
    id: "bed_black_metal",
    name: "Black Metal Bed Frame",
    category: "bed_frame",
    retailerId: "demo_home",
    retailerName: "Demo Home",
    source: "demo",
    priceCents: 32900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/black-metal-bed-frame",
    dimensions: { widthIn: 63, depthIn: 83, heightIn: 42 },
    materials: ["powder-coated steel"],
    colors: ["black"],
    styleTags: ["modern-contrast", "budget-refresh"],
    roomTags: ["bedroom"],
    availability: "in_stock",
    shippingDaysEstimate: 5,
    dimensionConfidence: 0.96
  },
  {
    id: "nightstand_oak_drawer",
    name: "Oak One-Drawer Nightstand",
    category: "nightstand",
    retailerId: "demo_home",
    retailerName: "Demo Home",
    source: "demo",
    priceCents: 14900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/oak-one-drawer-nightstand",
    dimensions: { widthIn: 20, depthIn: 16, heightIn: 24 },
    materials: ["oak veneer", "metal pull"],
    colors: ["oak", "brass"],
    styleTags: ["japandi-calm", "cozy-neutral", "warm-modern"],
    roomTags: ["bedroom"],
    availability: "in_stock",
    shippingDaysEstimate: 4,
    dimensionConfidence: 0.94
  },
  {
    id: "nightstand_black_slim",
    name: "Slim Black Nightstand",
    category: "nightstand",
    retailerId: "demo_home",
    retailerName: "Demo Home",
    source: "demo",
    priceCents: 9900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/slim-black-nightstand",
    dimensions: { widthIn: 18, depthIn: 15, heightIn: 23 },
    materials: ["engineered wood", "steel"],
    colors: ["black"],
    styleTags: ["modern-contrast", "budget-refresh"],
    roomTags: ["bedroom"],
    availability: "in_stock",
    shippingDaysEstimate: 3,
    dimensionConfidence: 0.91
  },
  {
    id: "rug_wool_neutral_8x10",
    name: "Neutral Wool Rug 8x10",
    category: "rug",
    retailerId: "demo_rugs",
    retailerName: "Demo Rugs",
    source: "demo",
    priceCents: 34900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/neutral-wool-rug-8x10",
    dimensions: { widthIn: 96, depthIn: 120, heightIn: 1 },
    materials: ["wool", "cotton backing"],
    colors: ["ivory", "sand", "charcoal"],
    styleTags: ["cozy-neutral", "japandi-calm", "warm-modern"],
    roomTags: ["bedroom", "living_room"],
    availability: "in_stock",
    shippingDaysEstimate: 6,
    dimensionConfidence: 0.99
  },
  {
    id: "rug_graphic_8x10",
    name: "Graphic Flatweave Rug 8x10",
    category: "rug",
    retailerId: "demo_rugs",
    retailerName: "Demo Rugs",
    source: "demo",
    priceCents: 21900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/graphic-flatweave-rug-8x10",
    dimensions: { widthIn: 96, depthIn: 120, heightIn: 1 },
    materials: ["cotton", "polyester"],
    colors: ["black", "white", "gray"],
    styleTags: ["modern-contrast", "budget-refresh"],
    roomTags: ["bedroom", "living_room", "dorm_room"],
    availability: "in_stock",
    shippingDaysEstimate: 4,
    dimensionConfidence: 0.98
  },
  {
    id: "dresser_oak_six_drawer",
    name: "Low Oak Six-Drawer Dresser",
    category: "dresser",
    retailerId: "demo_home",
    retailerName: "Demo Home",
    source: "demo",
    priceCents: 69900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/low-oak-six-drawer-dresser",
    dimensions: { widthIn: 58, depthIn: 20, heightIn: 32 },
    materials: ["oak veneer", "solid pine"],
    colors: ["oak"],
    styleTags: ["japandi-calm", "cozy-neutral", "warm-modern"],
    roomTags: ["bedroom"],
    availability: "low_stock",
    shippingDaysEstimate: 12,
    dimensionConfidence: 0.95
  },
  {
    id: "dresser_white_compact",
    name: "Compact White Dresser",
    category: "dresser",
    retailerId: "demo_home",
    retailerName: "Demo Home",
    source: "demo",
    priceCents: 29900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/compact-white-dresser",
    dimensions: { widthIn: 46, depthIn: 19, heightIn: 34 },
    materials: ["painted wood composite"],
    colors: ["white"],
    styleTags: ["budget-refresh", "modern-contrast", "cozy-neutral"],
    roomTags: ["bedroom", "dorm_room"],
    availability: "in_stock",
    shippingDaysEstimate: 6,
    dimensionConfidence: 0.9
  },
  {
    id: "lamp_ceramic_table",
    name: "Warm Ceramic Table Lamp",
    category: "lamp",
    retailerId: "demo_lighting",
    retailerName: "Demo Lighting",
    source: "demo",
    priceCents: 7900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/warm-ceramic-table-lamp",
    dimensions: { widthIn: 12, depthIn: 12, heightIn: 24 },
    materials: ["ceramic", "linen shade"],
    colors: ["cream", "linen"],
    styleTags: ["cozy-neutral", "japandi-calm", "warm-modern"],
    roomTags: ["bedroom", "living_room", "home_office"],
    availability: "in_stock",
    shippingDaysEstimate: 3,
    dimensionConfidence: 0.92
  },
  {
    id: "lamp_black_sconce",
    name: "Plug-In Black Wall Sconce",
    category: "lamp",
    retailerId: "demo_lighting",
    retailerName: "Demo Lighting",
    source: "demo",
    priceCents: 8900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/plug-in-black-wall-sconce",
    dimensions: { widthIn: 8, depthIn: 10, heightIn: 14 },
    materials: ["steel", "linen shade"],
    colors: ["black", "white"],
    styleTags: ["modern-contrast", "budget-refresh"],
    roomTags: ["bedroom", "home_office"],
    availability: "in_stock",
    shippingDaysEstimate: 5,
    dimensionConfidence: 0.82
  },
  {
    id: "curtains_linen_pair",
    name: "Linen Curtain Pair",
    category: "curtains",
    retailerId: "demo_textiles",
    retailerName: "Demo Textiles",
    source: "demo",
    priceCents: 12900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/linen-curtain-pair",
    dimensions: { widthIn: 100, depthIn: 2, heightIn: 96 },
    materials: ["linen", "cotton"],
    colors: ["natural", "oat"],
    styleTags: ["cozy-neutral", "japandi-calm", "warm-modern"],
    roomTags: ["bedroom", "living_room"],
    availability: "in_stock",
    shippingDaysEstimate: 4,
    dimensionConfidence: 0.87
  },
  {
    id: "curtains_white_black_trim",
    name: "White Curtains With Black Trim",
    category: "curtains",
    retailerId: "demo_textiles",
    retailerName: "Demo Textiles",
    source: "demo",
    priceCents: 9900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/white-curtains-black-trim",
    dimensions: { widthIn: 100, depthIn: 2, heightIn: 96 },
    materials: ["cotton blend"],
    colors: ["white", "black"],
    styleTags: ["modern-contrast", "budget-refresh"],
    roomTags: ["bedroom", "living_room", "dorm_room"],
    availability: "in_stock",
    shippingDaysEstimate: 4,
    dimensionConfidence: 0.84
  },
  {
    id: "art_landscape_pair",
    name: "Framed Landscape Print Pair",
    category: "wall_art",
    retailerId: "demo_art",
    retailerName: "Demo Art",
    source: "demo",
    priceCents: 11800,
    currency: "USD",
    purchaseUrl: "https://example.com/products/framed-landscape-print-pair",
    dimensions: { widthIn: 48, depthIn: 2, heightIn: 32 },
    materials: ["paper", "wood frame", "acrylic"],
    colors: ["sage", "ivory", "walnut"],
    styleTags: ["cozy-neutral", "japandi-calm", "warm-modern"],
    roomTags: ["bedroom", "living_room", "home_office"],
    availability: "in_stock",
    shippingDaysEstimate: 6,
    dimensionConfidence: 0.93
  },
  {
    id: "art_monochrome_grid",
    name: "Monochrome Grid Wall Art",
    category: "wall_art",
    retailerId: "demo_art",
    retailerName: "Demo Art",
    source: "demo",
    priceCents: 8900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/monochrome-grid-wall-art",
    dimensions: { widthIn: 42, depthIn: 2, heightIn: 30 },
    materials: ["paper", "black frame"],
    colors: ["black", "white"],
    styleTags: ["modern-contrast", "budget-refresh"],
    roomTags: ["bedroom", "living_room", "home_office"],
    availability: "in_stock",
    shippingDaysEstimate: 6,
    dimensionConfidence: 0.91
  },
  {
    id: "plant_floor_olive",
    name: "Faux Olive Floor Plant",
    category: "plant",
    retailerId: "demo_green",
    retailerName: "Demo Green",
    source: "demo",
    priceCents: 15900,
    currency: "USD",
    purchaseUrl: "https://example.com/products/faux-olive-floor-plant",
    dimensions: { widthIn: 24, depthIn: 24, heightIn: 72 },
    materials: ["polyester leaves", "ceramic pot"],
    colors: ["green", "white"],
    styleTags: ["cozy-neutral", "japandi-calm", "warm-modern"],
    roomTags: ["bedroom", "living_room", "home_office"],
    availability: "in_stock",
    shippingDaysEstimate: 5,
    dimensionConfidence: 0.88
  }
];

